
package io.klebe.ocid

object OCIDMeta {
    const val MODID = "ocid"

    // Tags is automatically generated by gradle
    const val NAME = Tags.MODNAME
    const val VERSION = Tags.VERSION

    const val DEPENDENCIES = "" +
            "required-after:forgelin;" +
            "required-after:integrateddynamics;" +
            "required-after:opencomputers"
}
